import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-premium-audit-return-premium-recovery",
  "engine": "recovery",
  "title": "Premium Audit Return-Premium Recovery",
  "shortTitle": "Premium Audit Return-Premium Recovery",
  "tagline": "Recalculate final premium audits and recover overcharges caused by classifications, exposures, uninsured subcontractors, or missing credits.",
  "industry": "Commercial Insurance Recovery",
  "buyer": "Commercial policyholders and brokers",
  "uiPort": 4664,
  "apiPort": 5664,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Premium Audit Return-Premium Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds in one accountable workflow. Recalculate final premium audits and recover overcharges caused by classifications, exposures, uninsured subcontractors, or missing credits.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Premium Audit Return-Premium Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("policy-exposure-terms","PRP01","Policy exposure terms","Execute policy exposure terms using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed policy exposure terms decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Policy exposure terms Reference","text","PRP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("classification-code-library","PRP02","Classification code library","Execute classification code library using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed classification code library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Classification code library Reference","text","PRP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("payroll-exposure-ingestion","PRP03","Payroll exposure ingestion","Execute payroll exposure ingestion using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed payroll exposure ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Payroll exposure ingestion Reference","text","PRP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("sales-exposure-ingestion","PRP04","Sales exposure ingestion","Execute sales exposure ingestion using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed sales exposure ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Sales exposure ingestion Reference","text","PRP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("subcontractor-cost-review","PRP05","Subcontractor cost review","Execute subcontractor cost review using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed subcontractor cost review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Subcontractor cost review Reference","text","PRP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("certificate-validation","PRP06","Certificate validation","Execute certificate validation using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed certificate validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Certificate validation Reference","text","PRP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("owner-officer-exclusion","PRP07","Owner officer exclusion","Execute owner officer exclusion using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed owner officer exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Owner officer exclusion Reference","text","PRP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("experience-modification-control","PRP08","Experience modification control","Execute experience modification control using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed experience modification control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Experience modification control Reference","text","PRP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("rate-and-factor-calculation","PRP09","Rate and factor calculation","Execute rate and factor calculation using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed rate and factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Rate and factor calculation Reference","text","PRP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("audit-worksheet-reconstruction","PRP10","Audit worksheet reconstruction","Execute audit worksheet reconstruction using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed audit worksheet reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Audit worksheet reconstruction Reference","text","PRP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("dispute-evidence-package","PRP11","Dispute evidence package","Execute dispute evidence package using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed dispute evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Dispute evidence package Reference","text","PRP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("carrier-negotiation-workflow","PRP12","Carrier negotiation workflow","Execute carrier negotiation workflow using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed carrier negotiation workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Carrier negotiation workflow Reference","text","PRP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("return-premium-calculation","PRP13","Return premium calculation","Execute return premium calculation using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed return premium calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Return premium calculation Reference","text","PRP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("refund-reconciliation","PRP14","Refund reconciliation","Execute refund reconciliation using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Refund reconciliation Reference","text","PRP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]}),
feature("policy-class-analytics","PRP15","Policy class analytics","Execute policy class analytics using policies, classifications, payroll, sales, subcontractor costs, certificates, audit worksheets, endorsements, invoices, and refunds.","Produce a governed policy class analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Policy / Audit Period","text","Policy / Audit Period · Standard Case"],["caseReference","Policy class analytics Reference","text","PRP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",796250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",963463],["domainDriver","Exposure Basis","select","Payroll",["Payroll","Sales","Subcontractor cost"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Policy exposure terms case","Classification code library case","Payroll exposure ingestion case","Sales exposure ingestion case","Subcontractor cost review case"]})
]);
